#!/bin/bash

# Basic configuration
URL=http://www.w3.org/2002/01/tr-automation/tr.rdf
FILE=$(basename "$URL")
STYLESHEET=w3c-rdf-to-bibtex.xsl
OUTPUT=w3c.bib

# Check for dependencies
for i in xsltproc wget; do
  if !(which $i &>/dev/null); then
    echo "Error: please install $i first."
    exit 1
  fi
done

wget -nv --timestamping "$URL"
xsltproc "$STYLESHEET" "$FILE" > w3c.bib

